### ISSUE TITLE
TokenList::deleteToken() might benefit from debug checks

### ISSUE THREAD

**Issue by Dmitry-Me** [danmar/simplecpp#103]
`TokenList::deleteToken()` is correct under assumption that `next != tok` and `prev != tok`. However these pre-conditions are guaranteed by the rest of the code and not known inside the function. This is why Coverity reports a variety of "double free" and "access after free" defects in cppcheck.

I'm not sure this change will work against Coverity reporting defects but it looks like the following would make assumptions clear (and maybe work against defects being reported):

    Token *prev = tok->previous;
    Token *next = tok->next;
    assert( prev != tok );
    assert( next != tok );

This would also require including `<cassert>` and doing that inside `simplecpp.h` header file would cause its inclusion into every translation unit which includes `simplecpp.h`. Perhaps it's worth moving the method into `simplecpp.cpp`

**Comment by danmar** [comment]
those assertions don't make sense to me.

**Comment by Dmitry-Me** [comment]
They check that no element has "next" and "prev" links set to itself. That's what you usually have in a double link list.

**Comment by danmar** [comment]
yes. that would mean the list is badly corrupt and it doesn't make sense to me to add these assertions.

I just think that Coverity shows a FP here. There is no problem with this code.

**Comment by Dmitry-Me** [comment]
Yes, Coverity shows an FP here and the reason for this is it doesn't know that list cannot be corrupt.

**Comment by danmar** [comment]
Don't try to fix false positives. Classify them as "False positive" in the web interface.
