### ISSUE TITLE
maybe std::string_view is good candicate for std::string in the Token class

### ISSUE THREAD

**Issue by asmwarrior** [danmar/simplecpp#105]
I see some comments in the source file:
```
/**
     * token class.
     * @todo don't use std::string representation - for both memory and performance reasons
     */
    class SIMPLECPP_LIB Token {
    public:
        Token(const TokenString &s, const Location &loc) :
            str(string), location(loc), previous(NULL), next(NULL), string(s) {
            flags();
        }

        Token(const Token &tok) :
            str(string), macro(tok.macro), location(tok.location), previous(NULL), next(NULL), string(tok.str) {
            flags();
}
```
Luckily, there are some back port header files for C++11 compiler. (std::string_view will comes in C++17)

BTW: do you use this simplecpp inside your cppcheck? What's the purpose for designing this C-preprocessor?
Thanks.

**Comment by danmar** [comment]
is that ported to C++03 also? simplecpp code is C++03.

yes the reason to design this was that we wanted to have a new better preprocessor in Cppcheck.

**Comment by danmar** [comment]
I believe that a "proper" preprocessor uses enum instead.

**Comment by asmwarrior** [comment]
> is that ported to C++03 also? simplecpp code is C++03.
Oh, Google simply find another one which support C++03. [satoren/string_view](https://github.com/satoren/string_view)

> I believe that a "proper" preprocessor uses enum instead.
Yes, in-fact, I'm one of the Code::Blocks developer, my main interest is to maintain the parser for the CodeCompletion feature. We also have a preprocessor, which do quite similar things, that is: the preprocessor just return a raw string to the Parser, and the Parser have to check the first character of the returned Token to see if it is an "identifier" like token. I guess the cppcheck are using the same "raw string" as a token.

The best idea is to use a Token class which as a "enum" field as the Token kind, and there is another string field for the actual "lexeme string". Some thing like my question here: [How to pass token kind with its associated information from lexer to preprocessor, then to parser](https://stackoverflow.com/questions/42041579/how-to-pass-token-kind-with-its-associated-information-from-lexer-to-preprocesso)

**Comment by danmar** [comment]
I think it's enough with the todo comment for now. No need to have a issue also.
