### ISSUE TITLE
What does "DUI" mean?

### ISSUE THREAD

**Issue by asmwarrior** [danmar/simplecpp#106]
```
    struct SIMPLECPP_LIB DUI {
        DUI() {}
        std::list<std::string> defines;
        std::set<std::string> undefined;
        std::list<std::string> includePaths;
        std::list<std::string> includes;
    };
```

Some doxygen style comments are needed here.

**Comment by amai2012** [comment]
**D**efines**U**ndefined**I**ncludes - what could be more descriptive? :wink:

**Comment by danmar** [comment]
would you feel ok with just an updated doxygen comment? It is for storing the preprocessor arguments (-D -U -I). Yes a longer name could be DefinesUndefinedIncludes.
