### ISSUE TITLE
suggestion: Handling operators in the first pass of the tokenization

### ISSUE THREAD

**Issue by asmwarrior** [danmar/simplecpp#107]
When reading and debug the code, I see that there is a function named
`combineOperators()`

This function happens in the last stage of the function
`void simplecpp::TokenList::readfile(std::istream &istr, const std::string &filename, OutputList *outputList)`
In the `readfile()` function, the first pass of the tokenization is a while loop, which has a if condition

```
        else {
            currentToken += ch;
        }
```
Where, the ch could be "=", but there maybe another "=" after the ch, if I remember correct, most parsers/lexers are handling the operators in the this else clause.

Another suggestion is that you can add a new field named "TokenKind" (enum type) to the Token class, this can avoid running the type check calls in the future, currently, you have a type check function as Token's member function:
```

        void flags() {
            name = (std::isalpha((unsigned char)str[0]) || str[0] == '_' || str[0] == '$');
            comment = (str.compare(0, 2, "//") == 0 || str.compare(0, 2, "/*") == 0);
            number = std::isdigit((unsigned char)str[0]) || (str.size() > 1U && str[0] == '-' && std::isdigit((unsigned char)str[1]));
            op = (str.size() == 1U) ? str[0] : '\0';
        }
```

The third suggestion is that I think the you can distinguish the "identifier" and the "number" kind token, currently, they are tokenized together, see the code:

```
        // number or name
        if (isNameChar(ch)) {
            const bool num = std::isdigit(ch);
            while (istr.good() && isNameChar(ch)) {
                currentToken += ch;
                ch = readChar(istr,bom);
                if (num && ch=='\'' && isNameChar(peekChar(istr,bom)))
                    ch = readChar(istr,bom);
            }

            ungetChar(istr,bom);
        } 
```

The last suggestion is that maybe the "preprocessor" stage can also be put in the single pass. I mean you don't need to first tokenize the tokens without preprocessor, and then run the preprocessor again on the Tokenlist. This can be combined in a single pass.

**Comment by danmar** [comment]
there are 4 suggestions here that can be solved indepently.. I want that you create 1 separate issue for each independant suggestion.

It sounds good to combine the operators directly if that is easy and does not have bad side effects.
Quick answers:
Adding a TokenKind enum sounds good.. however I want it to be really used there is not much point to add it if it isn't used.
splitting up parsing of names/numbers .. I don't want to have cloned code.
changing it to a single pass.. Cppcheck needs the raw tokens so it can extract the configurations etc. and there is a long term goal to avoid false positives when there is "hidden" code.
