### ISSUE TITLE
Error with raw string literal LR"("')"

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#112]
Transferred from https://trac.cppcheck.net/ticket/8309:

Found this issue while scanning the file ​https://github.com/vslavik/poedit/blob/master/src/syntaxhighlighter.cpp from the poedit project.
The original raw string literal that causes problems is:

    LR"(<\/?[a-zA-Z]+(\s+\w+(=(\w+|"[^"]*"|'[^']*'))?)*\s*\/?>)"

I hope i correctly reduced it to this example code (errormessage is the same):

>"cppcheck" --version
Cppcheck 1.82 dev

>"cppcheck" --enable=all --debug "raw_string_literal.cpp"
Checking raw_string_literal.cpp ...
[raw_string_literal.cpp:1]: (error) No pair for character ('). Can't process file. File is either invalid or unicode, which is currently not supported.

>type raw_string_literal.cpp
    std::wstring str = LR"("')";

I'm not sure if it is related to simplecpp, there are already several tests for raw string literals.

**Comment by amai2012** [comment]
https://github.com/danmar/simplecpp/blob/d2f5d34c40a0966082246fe58b284e73321919d3/simplecpp.cpp#L524 seems to neglect prefixes for raw strings.

**Comment by danmar** [comment]
Fixed by c368c82e425bfab12178ad11cb1b3db160acbff1
