### ISSUE TITLE
Wrong handling of hash hash

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#114]
Based on this Cppcheck ticket: https://trac.cppcheck.net/ticket/8331

Example code:

    #define A(XY)    X##Y = XY
    A(123);

Output from gcc:

    XY = 123;

Output from simplecpp:

    123 = 123;

**Comment by danmar** [comment]
the wrong issue was closed.

**Comment by amai2012** [comment]
@danmar But 5f19e505a149e40387c4bf3586389f3d12730e86 fixed this...

**Comment by danmar** [comment]
hmm yes.
