### ISSUE TITLE
handle '#include MACRO'

### ISSUE THREAD

**Issue by fnxweb** [danmar/simplecpp#119]
_cppcheck_ has for some time had problems with macros with **#include** statements. As of 1.77 _cppheck_ flags most of these situations as errors, which has exacerbated the situation.

Here's the most simple example.

```
#define INCLUDE_LOCATION ../somewhere
#define INCLUDE_FILE(F)  <INCLUDE_LOCATION/F.h>

// Error line
#include INCLUDE_FILE(header)

int main()
{
    return 0;
}


$ cppcheck-1.79 macroinclude.cpp
Checking macroinclude.cpp ...
[macroinclude.cpp:5]: (error) No header in #include
```
Further: the following does not work, but in this case quietly — no error, it just doesn't do the include.

```
// Second example
#define _1ASSTRING(token)  #token
#define AS_STRING(token)  _1ASSTRING(token)
#include AS_STRING(types.h)
```

When I investigated with _strace_, I got a slightly amusing output which gives me a hint as to what's going wrong (if not where)!

```
Checking macroinclude.cpp ...
open("NCLUDE_FIL", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
open("S_STRIN", O_RDONLY|O_LARGEFILE)   = -1 ENOENT (No such file or directory)
```

Although presumably the mistake it's making wouldn't occur if the macro expansion had happened.

**Comment by danmar** [comment]
I think this works now. For first example code, simplecpp reports:

    114.c:5: missing header: Header not found: <../somewhere/header.h>

For second example simplecpp reports:

    119.c:4: missing header: Header not found: "types.h"

When we "bump" simplecpp in cppcheck, cppcheck will also report these error messages.
