### ISSUE TITLE
No error message is written for the replacement list (##X) 

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#121]
There was this discussion in the cppcheck chat:
https://sourceforge.net/p/cppcheck/discussion/development/thread/991b2f5e/

Simplecpp should write a error message when invalid `##` usage is seen.

Code example:

    #define FOO(arg1type)  typedef void (T::*fnptr)(##arg1type);
    FOO(int)

**Comment by myGitAccount1** [comment]
Got some Visual studio code with ## that has happy (compiled with errors or warnings) and been in existence from vs6 to v2010  (see simplified example below):-
> v1.83 now shows error for ## but does not detect\report other issues in .cpp.
> v1.82 doesn't show error on ##, shows analysis error but does not detect\report other issues in .cpp.
> v1.69 doesn't show error on ## and detect\reports other issues in .cpp.

Can the new ## detection not prevent the other issues, errors, warnings, etc in the file from being detected \ shown?

.h
typedef enum _VALUES { THING1 = 0, THING2 = 1} VALUES;
#define MYMACRO(x)  functionName(##x, THING1)

.cpp
MYMACRO("test");           //from CppCheck v1.82 error from ## in this suppresses any other issues being reported
sprintf(s, "%s %s", arg1);  // like this one, or any other warning, error, style or performance issue.

**Comment by danmar** [comment]
if your code is invalid.. why don't you fix it? In my opinion this is a mistake in vs not a feature.. why would you put a ## there in the code.

**Comment by myGitAccount1** [comment]
Massive existing code base scanned with v1.6 reports 1000s of issues of varying severity. V1.8 same code base reported issues drop to 10s due to ## error taking presidence and supressing any other issues. 
## is not a show stopper / potential runtime failure but is preventing detection of issues that are.

**Comment by danmar** [comment]
so why don't you remove the ## in your code? It is a mistake in your code that has not been detected. I assume that there is just a macro or two that has this mistake in them.

**Comment by myGitAccount1** [comment]
The new Cpp check approach not to report any other analysis issues on a file when it detects this is worrying and suppresses the fanatics power of the CppCheck analysis capabilities.

If this approach is adopted then there can be no confidence in the CppCheck analysis results. e.g. Report or risk analysis, estimates of existing code bases can no longer be accurate. Fixing an error of this time can then result in report then returning 1000s more issues in the same code.

Until this approach is changed I will be using v1.69 or using other analysis tools.

**Comment by danmar** [comment]
sorry.. I want to know; why don't you remove the `##` in your code?

**Comment by danmar** [comment]
sorry.. I want to know; why don't you remove the `##` in your code?
