### ISSUE TITLE
Supply current builds via appveyor

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#122]
Appveyor could be used to provide current binaries. 
However I wonder why only debug builds are currently configured there?

**Comment by danmar** [comment]
the command line tool is just intended to be a demo tool.

**Comment by amai2012** [comment]
That's a very old issue...
Meanwhile I'd recommend artifacts from github action if any.

Maybe we should close this ticket...

**Comment by danmar** [comment]
yes github would be better. well I am not sure I see the use case. if people wants to try out the demo tool we could make a release.
