### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [danmar/simplecpp#123]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/danmar/simplecpp/blob/26bc3c9b73c55cf2be0b4034f3dc41edbd4d373d/main.cpp#L8 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by danmar** [comment]
main is just a simple test program.

but I think it would be good if the simplecpp::preprocess does not throw exceptions. I would like that it reports all errors/etc through `outputList`.

**Comment by danmar** [comment]
if you see that `simplecpp::preprocess` could throw exceptions that are not caught please reopen this ticket.

**Comment by elfring** [comment]
How will the support for C++ exceptions be evolving?

**Comment by danmar** [comment]
I want simplecpp to be exception safe.. that means we can't just throw some exception if we see something wrong.

**Comment by danmar** [comment]
yes. please feel free to look around in the simplecpp.cpp file. I would like that to be exception safe. main.cpp is just a demo application I don't care if it's not fully safe.

**Comment by elfring** [comment]
>… I don't care if it's not fully safe.

I prefer a different development approach so that the software demonstration will be better.

Your expectations for exception safety might be different from mine.
