### ISSUE TITLE
Lines starting with "#" but contain no preprocessor code seem to confuse simplecpp

### ISSUE THREAD

**Issue by versat** [danmar/simplecpp#125]
As reported [in the forum](https://sourceforge.net/p/cppcheck/discussion/general/thread/8a0a0174/) simplecpp seems to have problems with some include files from boost.
See for example [config.hpp](https://github.com/boostorg/preprocessor/blob/develop/include/boost/preprocessor/config/config.hpp)

For code like this (similar to how boosts config.hpp is written):
~~~cpp
#
# if 1
#  define a 1
# endif

int main()
{
    printf("%d", a);
}
~~~
simplecpp reports this error:
~~~
$ ./simplecpp include.hpp

include.hpp:4: syntax error: #endif without #if
~~~
Removing the single `#` at the top makes it work again.
simplecpp also fails in the same way if a comment follows a `#` like this:
~~~cpp
# //test
# if 1
#  define a 1
# endif

int main()
{
    printf("%d", a);
}
~~~
With gcc the output is just fine:
```
$ gcc -E include.hpp
# 1 "include.hpp"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "include.hpp"





int main()
{
    printf("%d", 1);
}
```

**Comment by amai2012** [comment]
http://en.cppreference.com/w/cpp/preprocessor says:
>The null directive (# followed by a line break) is allowed and has no effect.
