### ISSUE TITLE
Allow to disable #line in outputs

### ISSUE THREAD

**Issue by agners** [danmar/simplecpp#134]
I am using simplecpp to preprocess device tree files. The device tree compiler does not know `#line`. It would be nice if there is an option to disable emitting of `#line` directives.

**Comment by danmar** [comment]
how about the other options:
 1. copy and tweak simplecpp/main.cpp. It's just a small (97 lines) demonstration.
 2. postprocess the output. Something like `grep -v #line`.

**Comment by agners** [comment]
I am using `sed -i '/^#/ d'`  as a work around.

**Comment by danmar** [comment]
I close this as invalid.. please feel free to use the workaround.
