### ISSUE TITLE
Invalid ## usage when expanding macro

### ISSUE THREAD

**Issue by bnason-nf** [danmar/simplecpp#141]
When attempting to process this:

```
struct MyType {
    int x;
#   define ADD_OPERATOR(OP) void operator OP ## = (void) { x = x OP 1; }
    ADD_OPERATOR(+)
};
````

I get the following error from simplecpp:

`syntax error: failed to expand 'ADD_OPERATOR', Invalid ## usage when expanding 'ADD_OPERATOR'.`

**Comment by danmar** [comment]
thanks. yes this seems to be a bug

**Comment by Mike4Online** [comment]
I just installed **Cppcheck 2.6**, and it fails to handle `##` in macro definitions within .cpp files from all of my Visual C++ projects.  I get errors such as

`failed to expand 'LOGVERBOSE', Invalid ## usage when expanding 'LOGVERBOSE'.`

In my code the macro is defined as follows:

`#define LOGVERBOSE / ## /`

The end result is the macro becomes defined as //, so any statement beginning with LOGVERBOSE is commented out.  This is a handy technique for enabling and disabling logging statements.
