### ISSUE TITLE
 __LINE__ is not resolved properly

### ISSUE THREAD

**Issue by stayprivates** [danmar/simplecpp#142]
Created a ticket on trac.cppcheck.net (#8895)  but to file a bug report here, so here goes:

    #define SAFE_LOCAL_ARRAY_TOKENPASTE(x, y) x##y
    #define SAFE_LOCAL_ARRAY_TOKENPASTE2(x, y) SAFE_LOCAL_ARRAY_TOKENPASTE(x, y)
    #define SAFE_LOCAL_ARRAY_UNIQUE SAFE_LOCAL_ARRAY_TOKENPASTE2(Unique_, __LINE__)
    #define SAFE_LOCAL_ARRAY(type,var,size) type SAFE_LOCAL_ARRAY_UNIQUE[(size)];\
	LocalArray<type> var(SAFE_LOCAL_ARRAY_UNIQUE, (size))
	
    template<typename T>
    class LocalArray
    {
    	public:
	
            LocalArray(T val[],  int dim);
    };

    void foo()
    {
        SAFE_LOCAL_ARRAY(float, tabXminSmooth, 10);
        SAFE_LOCAL_ARRAY(float, tabXmaxSmooth, 10);
    }

If compile with g++ -E, it will show that LINE gets resolved to line number of the call of SAFE_LOCAL_ARRAY. In my case

    float Unique_19[(10)]; LocalArray?<float> tabXminSmooth(Unique_19, (10));
    float Unique_20[(10)]; LocalArray?<float> tabXmaxSmooth(Unique_20, (10));

But cppcheck will resolve LINE to the line number of the SAFE_LOCAL_ARRAY_UNIQUE macro, which is 3 . So instead of the variables Unique_19 and Unique_20 cppcheck sees two Unique_3 variables. Hence it reports "Local variable Unique_3 shadows outer variable".

Regards,

**Comment by danmar** [comment]
Could you please simplify the test code. You can for instance look at `cppcheck -E` output.

I imagine that it's possible to reduce the code to 2-3 lines of code.

**Comment by danmar** [comment]
Simplified code:

    #define TOKENPASTE(x, y) x##y
    #define TOKENPASTE2(x, y) TOKENPASTE(x, y)
    #define UNIQUE_LINE TOKENPASTE2(Unique_, __LINE__)
    
    UNIQUE_LINE
    UNIQUE_LINE
