### ISSUE TITLE
Multiline raw string literals produce invalid code

### ISSUE THREAD

**Issue by versat** [danmar/simplecpp#149]
Valid C++11 code such as this
```c++
#include <cstdio>

int main()
{
    printf(R"(Hello 
    world!)");
}
```
is processed to this by simplecpp:
```c++
int main ( )
{
printf ( "Hello 
    world!") ;
}
```
which is invalid:
```
$ ./simplecpp rstring.cpp | g++ -Wall -Wextra -xc++ -
rstring.cpp:1: missing header: Header not found: <cstdio>
<stdin>:5:10: warning: missing terminating " character
<stdin>:5:10: error: missing terminating " character
<stdin>:6:11: warning: missing terminating " character
<stdin>:6:11: error: missing terminating " character
<stdin>: In function ‘int main()’:
<stdin>:6:5: error: ‘world’ was not declared in this scope
```
If every real newline character in the raw string would be prepended by `\n\` the output with the newlines would be preserved and also the line numbers of the code do not change.
I would expect something like this as output from simplecpp then:
```c++
int main ( )
{
printf ( "Hello \n\
    world!") ;
}
```

**Comment by danmar** [comment]
I only think it is the debug output that is "wrong". I assume the string is written in a single token.

If you get such errors with the debug output in some edge cases I don't worry much, as long as the actual token output is correct.

**Comment by amai2012** [comment]
I think there have been changes for string literals, e.g. 752e698b66fef36301e64fc66adc2c4d09536fa8
Did they cure this problem?

**Comment by versat** [comment]
Hmm, I am not sure how the token output from simplecpp looks like.
Would it make sense to add some command line parameter that outputs the tokens?
I tested the example code with Cppcheck and it looks well, issues are found and no syntax errors or so are reported.
So I guess the tokens are correct. I will close this issue, I do not see any problem at the moment.

**Comment by danmar** [comment]
> Would it make sense to add some command line parameter that outputs the tokens?

Yes that sounds good. For now I think `cppcheck --dump` can be used also.. the `<rawtokens>` should be taken directly from simplecpp.. as far as I remember.
