### ISSUE TITLE
don't report missing headers in hidden code

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#15]
Ticket from cppcheck: http://trac.cppcheck.net/ticket/3331

Example code

    #define MYCOOLDEFINE 0
    #if (MYCOOLDEFINE==0)
    #include "doesnotexist.h"
    #endif

simplecpp output:

    3331.c:3: missing include: Header not found: "doesnotexist.h"

**Comment by danmar** [comment]
bad code. the missing header should be reported in that code.

**Comment by amai2012** [comment]
Why?

**Comment by danmar** [comment]
I did not see it neither at first. but the #include is not hidden.
