### ISSUE TITLE
Bad performance when using many -I directives

### ISSUE THREAD

**Issue by HolgiHo** [danmar/simplecpp#151]
@danmar Thanks for merging #145 and #150 into master. On my large solution (~5000 cpp files, using >10000 header files from external libraries) this already gives me a speedup of factor 3.

However, there is more potential for performance improvement (again factor ~3):
- Every time when resolving an #include path, cppcheck checks if a such a file exists at all locations given by compiler include paths (-I).
- I am using about 25 such -I directives due to the large number of external libraries.
- That means, simplecpp must check up to 25 locations for each #include directive, but usually the required header file exists only in 1 of these locations.
- Profiling in Visual Studio showed that ~40% of the total Cppcheck runtime is spent in ifstream.open

I could reach a speedup of factor ~3 by implementing the following:
- in openHeader: remember all file paths of files known not to exist in a "nonExistingFilesSet"
- in simplecpp::simplifyPath: cache results in a map (path -> simplifiedPath)

I already submitted the necessary changes in PR #144, but we decided to split up this PR into smaller pieces.

A word about thread-safety:
- In contrast to function realFilename, which is only used on Windows, the 2 new caches are used on all platforms (openHeader and simplifyPath are called on all platforms).
- At first sight this would mean we would have to implement a platform-independent synchronization mechanism for cache access. This would be difficult without C++11 std lib.
- However, we are lucky: Cppcheck uses multi-threading only on Windows platform. On Linux/Unix it uses forking, i.e. we simply can omit synchronization on Linux/Unix, because each cache is local to one forked process. (Unfortunately, this means caching is less effective.)

@danmar If you agree, I would submit another PR implementing the described cache features. I simply wanted to hear your opion before :-) Thank you!

**Comment by danmar** [comment]
This is a tough question. The intention with `simplecpp` is that it will be a general purpose library. I was hoping that it would be used by some other projects but so far it's only used by Cppcheck as far as I know. I am not sure that we want to break multithreading in posix.

If you can design this so the caches are only used in windows I think I would prefer that. However I do not want to have lots of code complexity to achieve that. Is a clean simple solution possible?

**Comment by HolgiHo** [comment]
I understand your concerns. Yes, I think a clean simple solution is possible. I will submit a PR within the next few days.
