### ISSUE TITLE
infinite loop when file #includes itself

### ISSUE THREAD

**Issue by matthiaskrgr** [danmar/simplecpp#17]
to create a testcase:
````bash
echo "#include \"foobar.c\"" > foobar.c
simplecpp ./foobar.c
````

simplecpp does not notice that the file includes itself and crunch for a very long time until eventually running out of memory at some point (I didn't wait 'till that happened, just observed memory consumption slowly rising)

**Comment by danmar** [comment]
it is ok for a file to include itself. so we don't want to disallow that.

gcc includes the file 400 times and then write:

    /foobar.c:1:20: error: #include nested too deeply

I guess we should have similar behaviour.

**Comment by matthiaskrgr** [comment]
What was the behaviour of the old preprocessor in this case?
I think it didn't have problems with that.

**Comment by danmar** [comment]
it did not include a file twice.
