### ISSUE TITLE
simplecpp silently ignores when an explicitly included file does not exist

### ISSUE THREAD

**Issue by versat** [danmar/simplecpp#183]
This has been reported in the Cppcheck forum:
https://sourceforge.net/p/cppcheck/discussion/general/thread/f20832cc83/

If `simplecpp` is called with `-include=<file>`, and the file does not exist, there is no error message. `simplecpp` just ignores the file. This could be very confusing for users since the real issue thus can be hidden for a long time.
At [simplecpp:2426](https://github.com/danmar/simplecpp/blob/71adfce5898bad0a059938948b4d9e1ab767189f/simplecpp.cpp#L2426) a not existing file is simply ignored.
GCC aborts with a fatal error in the same case.
To not break the compatibility, `simplecpp` could be changed to print some warning so the user knows that the file is not included but otherwise behave as before.
I suggest the same handling for include files that exist but can not be opened for some reason.

**Comment by versat** [comment]
@danmar Would it be ok to print an error message to `stderr` (or `stdout`?) in that case to inform the user? I could create a PR for that.

**Comment by danmar** [comment]
@versat I do not think a library should print to stderr or stdout directly. Please generate an OutputListItem error message so the clients can handle this.
Imho it's fine if this is a fatal error. This is very likely something that the user really wants to fix.
