### ISSUE TITLE
fails to print filename in message when configuration is skipped due to undef value

### ISSUE THREAD

**Issue by matthiaskrgr** [danmar/simplecpp#20]
````c
#ifdef UNDEFINED
UNDEFINED;
#endif
````
with --enable=all on simplecpp gets us:
````
Checking bla.c...
Checking bla.c: UNDEFINED...
[:1]: (information) Skipping configuration 'UNDEFINED' since the value of 'UNDEFINED' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
````

it should be ````[bla.c:1]: (information)```` but it is ````[:1]: (information) ````

**Comment by danmar** [comment]
This is not a simplecpp issue. Configurations are extracted and validated by Cppcheck.

**Comment by danmar** [comment]
Fixed by https://github.com/danmar/cppcheck/commit/695b1f0ef3d2cf65129a2b1425cc6d093f656f07
