### ISSUE TITLE
Defect: &a ## b

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#202]
cppcheck fails to preprocess the code below:

```
> cppcheck --version
Cppcheck 2.3
> cppcheck -E main.c
main.c:1:0: error: failed to expand 'CONCAT', Invalid ## usage when expanding 'CONCAT'. [preprocessorErrorDirective]
#define CONCAT(x, y) x##y
^

```

main.c:

```
#define CONCAT(x, y) x##y

CONCAT(&a, b)
```

gcc handles it fine:

```
> gcc -E main.c
# 1 "main.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "main.c"


&ab
```

**Comment by mavik1** [comment]
I was able to work around the issue as follows:

```
&CONCAT(a, b)
```

**Comment by danmar** [comment]
ok good. thanks for reporting this issue..

**Comment by mavik1** [comment]
This was not an issue with cppcheck 1.82.

**Comment by danmar** [comment]
To clarify.. I do not feel that a workaround is a good solution. We need to fix this properly. But it's good you have a temporary workaround..

**Comment by danmar** [comment]
would it be possible to see what the gcc output is?

Is it 1 token "&ab" or two tokens "&" and "ab". the token "&ab" would be invalid and then the behavior is undefined.

**Comment by mavik1** [comment]
The gcc output is in the original post, or are you after something additional?

**Comment by danmar** [comment]
the output from a preprocessor is not plain text. it is tokens.

"&ab" would be an invalid token. that is not an operator and it is not a name. The parser needs to have "&" and "ab". and then it can determine that the "&" is a operator and "ab" is the operand.

**Comment by danmar** [comment]
sometimes we want to handle tokens in a macro parameter together and here is seems we want to handle the tokens separated.

See output from:

    #define A(B)  #B
    A(123+456)

**Comment by mavik1** [comment]
In the original code from which I provided the cutdown example, &ab gets assigned to a void * pointer. So gcc interprets `ab` as a variable name and `&` as the address-of operator. Is that the information you were after?

**Comment by danmar** [comment]
I have the feeling that this is not well defined code. I might be wrong.. the preprocessor rules are tricky.

**Comment by danmar** [comment]
I tested msvc preprocessor also. That also seemed to output "&" and "ab".

**Comment by keinflue** [comment]
I ran into the same issue and submitted a PR for this.

This seems well-defined. The argument is supposed to be interpreted as a token sequence which is substituted and then only the last token in that list is supposed to be concatenated. See §6.10.3.3p2 and p3 of C11 (n1570).
