### ISSUE TITLE
simplecpp::TokenList::TokenList() fails on string containing '\\' (backslash char literal)

### ISSUE THREAD

**Issue by chrchr-github** [danmar/simplecpp#227]
The problem seems to be in `readUntil()`. This leads to silent failure of some test cases in cppcheck (see here: https://trac.cppcheck.net/ticket/10238)

**Comment by chrchr-github** [comment]
This should do it:
~~~
std::istringstream str{ std::string("bool f(char c) { return c != '\\'; }") };
simplecpp::OutputList outputList;
std::vector<std::string> filenames;
simplecpp::TokenList tokens(str, filenames, {}, &outputList);
~~~

**Comment by chrchr-github** [comment]
Looking at the string some more, I recognized that the backslash needs to be double-escaped:
`"bool f(char c) { return c != '\\\\'; }"`
The same goes for the test cases in cppcheck.

**Comment by danmar** [comment]
ah thanks!
