### ISSUE TITLE
Fail to expand macros

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#293]
Example code:
```
#define bitmask(name) setbits(name##_START, name##_BITS)
#define field(name, value) (((value) << name##_START) & name##_MASK)
#define FOO_START 54
#define FOO_BITS 1
#define FOO_MASK bitmask(FOO)
#define FOO field(FOO, 0b1)
FOO_MASK; 
```
simplecpp output:

a.c:1: syntax error: failed to expand 'FOO_MASK', Invalid ## usage when expanding 'bitmask': Unexpected token ')'

**Comment by liuluheng** [comment]
I also encounter the problem, cppcheck outputs below

```
boost/boost/preprocessor/logical/bitor.hpp:27:0: error: failed to expand 'BOOST_MPL_AUX_NA_SPEC2', Invalid ## usage when expanding 'BOOST_PP_BITOR_I': Unexpected token ')' [preprocessorErrorDirective]
#    define BOOST_PP_BITOR_I(x, y) BOOST_PP_BITOR_ ## x ## y
^
```

any workaround for this?

**Comment by danmar** [comment]
@liuluheng I typically do not include the boost headers when I run cppcheck. maybe that is a workaround that will work for you.

Some "hack" in the source code could then be needed:
