### ISSUE TITLE
Nested macros are not (always) expanded

### ISSUE THREAD

**Issue by versat** [danmar/simplecpp#31]
See original thread at cppcheck (https://sourceforge.net/p/cppcheck/discussion/general/thread/f6c4e29d/)

Code like this:
```C
#define BUTTON_PORT_NUMBER 2
#define BTN_PIEZO_PIN (0x04)

/// Helper macro to concatenate the parameters
#define CONCATENATOR(x, y) x ## y
/// Helper macro to evaluate the parameters before concatenating
#define EVALUATOR(x, y) CONCATENATOR(x, y)
/// Helper macro to evaluate button port number and add it to 'P'
#define BUTTON_PORT EVALUATOR(P, BUTTON_PORT_NUMBER)

/// Direction port for button
#define BUTTON_PORT_DIR  (EVALUATOR(BUTTON_PORT, DIR))

void func(void)
{
    BUTTON_PORT_DIR &= (uint8_t)(~BTN_PIEZO_PIN);
}
```
Results in this code:
```C
void func ( void )
{
 (  EVALUATOR(P,2)DIR  ) &= ( uint8_t ) ( ~  (  0x04  ) ) ;
}
```
It should be:
```C
void func ( void )
{
 (  P2DIR  ) &= ( uint8_t ) ( ~  (  0x04  ) ) ;
}
```

**Comment by tortoisedoc** [comment]
This appears to be still present in 1.76.1; try the following code: 
`
#define GETMYID(a) ((a))+1

void foo(int a, ...)
{

}

#define FIGHT_FOO(c, ...) \
           foo(c, 3, 4, 5, ##__VA_ARGS__);

int main(){
        GETMYID(GETMYID(a));
        foo(GETMYID(a));
        FIGHT_FOO(1, GETMYID(a));
}
`

**Comment by danmar** [comment]
could you open a new issue for that. I have reduced your code example:

    #define GETMYID(a) ((a))+1
    #define FIGHT_FOO(c, ...) foo(c, ##__VA_ARGS__)
    FIGHT_FOO(1, GETMYID(a));

The gcc -E says:

    foo(1, ((a))+1);

And simplecpp says:

    foo ( 1 , GETMYID ( a ) ) ;

**Comment by tortoisedoc** [comment]
Sorry, was on vacation.
Here it is : https://github.com/danmar/simplecpp/issues/66
