### ISSUE TITLE
Spacing errors when file is included a second time

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#33]
main.c:
```
#define FN_NAME function1

#include "function.c"

#undef FN_NAME
#define FN_NAME function2

#include "function.c"
```
function.c:
```
char * FN_NAME(void)
{
	return NULL;
}
```
```
> cppcheck --version
Cppcheck 1.75
> cppcheck -q -E main.c

#line 1 "function.c"
char *  function1 ( void )
{
return NULL ;
}char* function2(void){returnNULL; }
> 
```

**Comment by danmar** [comment]
I believe that is just the stringify() function that does not handle well when the line number decrease.

of course this is not good for cppcheck as it currently uses:
  preprocess => stringify => tokenize => cppcheck tokens

but this will be fixed in cppcheck sooner or later so it won't rely on "stringify".

**Comment by mavik1** [comment]
The cppcheck symptom of this problem that I observed was false positives. For example if in function.c we have:
```
char * FN_NAME(void)
{
    char *ptr = NULL;
    return ptr;
}
```
Then cppcheck complains that `ptr` is assigned a value that is never used because it sees `returnptr` instead of `return ptr`.

**Comment by danmar** [comment]
yes.

**Comment by danmar** [comment]
would you be interested to fix it? I believe the stringify should add a "#line.." directive in the output when the line decrease and update the "location".

**Comment by mavik1** [comment]
Given my patch acceptance rate, I'm a little reluctant to implement a fix :)

**Comment by danmar** [comment]
:-(

I hope you will try again. there was no technical problems with your patches as far as I know.

It was unfortunate timing for some.. as I was in the middle of the rewrite of the preprocessor. and then I forgot about the 6028 patch until you wrote "Is there something I need to change for this patch to be accepted?". sorry about that.

**Comment by mavik1** [comment]
This issue is present in cppcheck 1.76.1. It is possible to reopen this ticket?

**Comment by danmar** [comment]
Do not open this ticket. simplecpp seems to work.

    daniel@debian:~/simplecpp$ ./simplecpp 33.c 
    
    #line 1 "33.h"
    char * function1 ( void )
    {
        return NULL ;
    }
    #line 1 "33.h"
    char * function2 ( void )
    {
    return NULL ;
    }

Cppcheck -E output is weird:
'
    daniel@debian:~/simplecpp$ ~/cppcheck/cppcheck -E 33.c 
    Checking 33.c ...
    
    #line 1 "33.h"
    char *  function1 ( void )
    {
    return NULL ;
    }char* function2(void){returnNULL; }

If you want .. feel free to open a ticket about that in the Cppcheck trac. I don't know if there is a "bug" in cppcheck, maybe it's just the -E output that is weird. Please investigate if the tokens, ast, symboldatabase, etc are generated properly.

**Comment by mavik1** [comment]
Ticket created: http://trac.cppcheck.net/ticket/7786
