### ISSUE TITLE
simplecpp fails to include file when name is defined by a macro

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#34]
include.h:

```
int i;
```

main.c:

```
#define INCLUDE_FILE "include.h"
#include INCLUDE_FILE
```

```
> cppcheck --version
Cppcheck 1.75
> cppcheck -q -E main.c

>
```

**Comment by danmar** [comment]
This is a duplicate of #3

**Comment by mavik1** [comment]
This issue is present in cppcheck 1.76.1. Is it possible to reopen the ticket?

**Comment by danmar** [comment]
I can confirm that it does not work with simplecpp HEAD

    daniel@debian:~/simplecpp$ ./simplecpp 34.c 
    
    34.c:2: missing header: Header not found: INCLUDE_FILE
