### ISSUE TITLE
Invalid code causing a crash

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#39]
Invalid test code taken from boost _wave_ https://github.com/boostorg/wave/blob/develop/test/testwave/testfiles/t_6_047.cpp causes a crash.

    #define CON(a, b)  a ## b ##
    CON(1, 2)

It was found via daca2...

**Comment by amai2012** [comment]
It might be a good idea to have a testrun on the whole set of tests written for wave.

**Comment by danmar** [comment]
yes I think also that would be a good idea.
