### ISSUE TITLE
Test failures on cygwin

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#41]
Running the tests as of b50ced8ac14f8debab9e85e78036f881ff2b3965 in cygwin (64bit) results in:

```
$ make test
g++ -fsyntax-only simplecpp.cpp && ./testrunner && python run-tests.py
TODO -E testsuite/clang-preprocessor-tests/c99-6_10_3_4_p5.c
TODO -E testsuite/clang-preprocessor-tests/c99-6_10_3_4_p6.c
FAILED -E testsuite/clang-preprocessor-tests/clang_headers.c
TODO -DA=1 -E testsuite/clang-preprocessor-tests/cxx_compl.cpp
TODO -E testsuite/clang-preprocessor-tests/cxx_oper_keyword_ms_compat.cpp
TODO -E testsuite/clang-preprocessor-tests/expr_usual_conversions.c
FAILED -E testsuite/clang-preprocessor-tests/has_attribute.cpp
TODO -E -Dfoo='bar\' testsuite/clang-preprocessor-tests/macro_backslash.c
TODO -E testsuite/clang-preprocessor-tests/macro_expand.c
TODO -E testsuite/clang-preprocessor-tests/macro_fn_comma_swallow.c
TODO -E testsuite/clang-preprocessor-tests/macro_fn_comma_swallow2.c
TODO -E -DNAMED testsuite/clang-preprocessor-tests/macro_fn_comma_swallow2.c
TODO -E testsuite/clang-preprocessor-tests/macro_fn_disable_expand.c
TODO -E testsuite/clang-preprocessor-tests/macro_fn_lparen_scan.c
TODO -E testsuite/clang-preprocessor-tests/macro_paste_commaext.c
TODO -E testsuite/clang-preprocessor-tests/macro_paste_hard.c
TODO -E testsuite/clang-preprocessor-tests/macro_rescan_varargs.c
TODO -E testsuite/clang-preprocessor-tests/stdint.c
TODO -E -Dint=a -Duint=b -D_t=c -DINT=d -DUINT=e -D_MIN=f -D_MAX=g testsuite/clang-preprocessor-tests/stdint.c
TODO -E -DTEST1 testsuite/clang-preprocessor-tests/stringize_misc.c
TODO -E testsuite/gcc-preprocessor-tests/diagnostic-pragma-1.c
FAILED -E testsuite/gcc-preprocessor-tests/normalize-3.c
TODO -E testsuite/gcc-preprocessor-tests/pr45457.c
TODO -E testsuite/gcc-preprocessor-tests/pr57580.c
FAILED -E testsuite/gcc-preprocessor-tests/pr63831-1.c
FAILED -E testsuite/gcc-preprocessor-tests/pr63831-2.c
FAILED -E testsuite/gcc-preprocessor-tests/pr65238-1.c
FAILED -E testsuite/gcc-preprocessor-tests/ucnid-2011-1.c
FIXED pr58844-1.c
FIXED pr58844-2.c
Number of tests: 176
Number of skipped: 15
Number of todos: 21
Number of failed: 7
```

I assume the FAILURES are all unexpected?

**Comment by amai2012** [comment]
Can this be related to http://trac.cppcheck.net/ticket/7725 "Include in source directory not found?!"?

**Comment by danmar** [comment]
> I assume the FAILURES are all unexpected?

Yes they are unexpected.

Also those "FIXED" are unexpected. They don't work in Linux.

**Comment by amai2012** [comment]
Are there any flags to produce a more verbose output?

**Comment by danmar** [comment]
no .. but feel free to add such flag.

**Comment by amai2012** [comment]
Do those tests work for you on Windows? I wonder if that is a platform issue.

**Comment by danmar** [comment]
hmm.. I get FIXED now on Linux too.

**Comment by danmar** [comment]
I took care of those FIXED : see 6c55e172799390905dba6719ff9247f7f3290fca

The testscript will now make sure they PASS. Otherwise it will say FAILED.

**Comment by amai2012** [comment]
Confirmed.
Now 7 FAILED remaining.

**Comment by danmar** [comment]
gcc in linux and cygwin generates somewhat different output. It might be because I have different gcc versions or because gcc was compiled with different settings.

The clang_headers.c failed because <limits.h> was different in linux and cygwin. I skip that test.

in my linux box gcc does not handle __has_attribute(). Therefore simplecpp pass in linux but fails in cygwin when that is used. For now I will skip these but maybe it would be best to handle __has_attribute().

in my linux box the code "\u00a0" generates a "\u00a0" token. however in cygwin I get "\u000000a0". I assume these are the same. But simplecpp always outputs "\u00a0" so it will fail in cygwin. I will skip these tests.
