### ISSUE TITLE
Null dereference in simplifySizeof() on unterminated "#elif sizeof" call

### ISSUE THREAD

**Issue by Barro** [danmar/simplecpp#59]
Unterminated sizeof call at #elif conditional directive makes simplecpp to do a null dereference at simplifySizeof() function:

```
#elif sizeof(d
```

This results in following GDB stack backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
(anonymous namespace)::simplifySizeof (expr=..., sizeOfType=...) at simplecpp.cpp:1678
1678                while (tok2->op != ')')
(gdb) p tok2
$1 = (simplecpp::Token *) 0x0
(gdb) bt
#0  (anonymous namespace)::simplifySizeof (expr=..., sizeOfType=...) at simplecpp.cpp:1678
#1  0x0000000000409b21 in (anonymous namespace)::evaluate (expr=..., sizeOfType=...) at simplecpp.cpp:1743
#2  0x00000000004111e1 in simplecpp::preprocess (output=..., rawtokens=..., files=..., filedata=..., dui=.
#3  0x00000000004041bd in main (argc=2, argv=0x7fffffffd4e8) at main.cpp:60
```

This happens with simplecpp revision d1c995c03515d289c7aa7246a74d666fd012c4eb. This looks like issue #46 but with within different conditional directive and with next level sizeof() processing style.

**Comment by amai2012** [comment]
IMHO that has been fixed meanwhile.

**Comment by danmar** [comment]
I close this. Feel free to reopen if it can be reproduced.
