### ISSUE TITLE
Incomplete hex number value results in undefined simplifyNumbers()/stringToULL() behavior

### ISSUE THREAD

**Issue by Barro** [danmar/simplecpp#62]
Following code with a cut hexadecimal number causes undefined behavior in stringToULL() function (called from simplifyNumbers() function):

```
#if 0x
```

Basically if a supposed number begins with characters indicating a hexadecimal value but is not really a number, stringToULL() constructs an empty std::istringstream object that is used to construct the return value:

```
unsigned long long stringToULL(const std::string &s)
{
    unsigned long long ret;
    bool hex = (s.compare(0, 2, "0x") == 0);
    std::istringstream istr(hex ? s.substr(2) : s); // this has value of empty string ""
    if (hex)
        istr >> std::hex;
    istr >> ret; // this line assigns undefined value to "ret"
    return ret;
}
```

This happens with simplecpp revision d1c995c03515d289c7aa7246a74d666fd012c4eb and can be detected by Valgrind's "Use of uninitialised value" error: [uninitialized-value-cut-hexadecimal-number.txt](https://github.com/danmar/simplecpp/files/585327/uninitialized-value-cut-hexadecimal-number.txt)

**Comment by amai2012** [comment]
That issue should be resolved now. (I cannot close this issue, probably just the owner may close issues?!)
