### ISSUE TITLE
realFileName() fails on Windows with relative paths

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#68]
Analysis of http://trac.cppcheck.net/ticket/7781 "Failure to find include file under windows" suggests that `realFileName()` fails on Windows in that scenario.
"..\dir1\dir2\include1.h" gets changed to "dir0\dir1\dir2\include1.h" which is a relative path which does not correspond to the current directory or the base for include paths.

**Comment by danmar** [comment]
I hope this works now. I could reproduce the issue with cygwin64.
