### ISSUE TITLE
define not resolved in use of freetype headers

### ISSUE THREAD

**Issue by mirage83** [danmar/simplecpp#72]
As a user of freetype2 it is common to do:
#include <ft2build.h>
#include FT_FREETYPE_H

With cppcheck 1.78 the following error is printed:
**(error) No header in #include**

The _<ft2build.h>_ includes _<freetype/config/ftheader.h>_ which defines FT_FREETYPE_H among others.

It seems like the define isn't resolved correctly.

NOTE: The path to the freetype2-headers must be given with -I (typically /usr/include/freetype2).

**Comment by amai2012** [comment]
Issue #3 was quite similar!?
I still get that error when trying to include boost headers.

**Comment by amai2012** [comment]
Did ec50c81 fix this?

**Comment by mirage83** [comment]
I retested the issue with cppcheck 1.83 which contains the mentioned patch.
With that the error didn't occur anymore.

**Comment by danmar** [comment]
ok :-(

I hope somebody will create a small test case and create a new issue for that.

I would say this issue is fixed
