### ISSUE TITLE
Incorrectly preprocessed cpp file

### ISSUE THREAD

**Issue by engycz** [danmar/simplecpp#79]
File in attachment [b.zip](https://github.com/danmar/simplecpp/files/1057796/b.zip) is incorrectly preprocessed.

simplecpp preprocessed:
```
char x ;

 _PROCES2  ( B46 , "X"  )
{
x = 6 ;
}
```

gcc preprocessed:
```char x;

void Proces(void)
{
  x = 6;
}```

**Comment by amai2012** [comment]
It might be convenient to present the input here, it's not too big:
```C
#define __VFUNC2(name, n)  name##n

#define PROCES(...) __VFUNC2(_PROCES, 2) (__VA_ARGS__)
#define _PROCES2(M, DESCR) void Proces(void)

char x;

PROCES(B46, "X")
{
  x = 6; 
}
```

**Comment by danmar** [comment]
simplified example code:

    #define A  F
    #define FOO(X,Y) A(X,Y)
    #define F(X, Y) X Y
    
    FOO(1,2)
