### ISSUE TITLE
simplifyPath() capitalizes windows drive letters

### ISSUE THREAD

**Issue by x29a** [danmar/simplecpp#85]
cppcheck tests [started acting up](https://ci.appveyor.com/project/danmar/cppcheck/history) after a bump of simplecpp because it seems that a call to [simplifyPath()](https://github.com/danmar/simplecpp/blob/master/simplecpp.cpp#L1784) changes the windows drive letter from small to capital (see [PR #919](https://github.com/danmar/cppcheck/pull/919)).

I would suggest that the capitalization is kept so file access works on case-sensitive filesystem (like windows NTFS).

Hence [realFileName()](https://github.com/danmar/simplecpp/blob/master/simplecpp.cpp#L1681) needs to be adjusted.

**Comment by danmar** [comment]
I merged pull request 86
