### ISSUE TITLE
simplecpp fails on invalid content in #if 0 section

### ISSUE THREAD

**Issue by amai2012** [danmar/simplecpp#91]
simplecpp produces a hard failure
```
 ../a.cpp:3: syntax error: No pair for character ('). Can't process file. File is either invalid or unicode, which is currently not supported.
```
 on
```c
void func() {
#if 0
it's a bug
#endif
}
```

cpp (from GNU) issues a warning only about an unterminated ' 

This in turn causes a syntax error in cppcheck on a reasonable source file.

**Comment by asmwarrior** [comment]
My point here is that for simplicity, simplecpp won't need to fix this bug.

**Comment by amai2012** [comment]
Another related ticket: https://trac.cppcheck.net/ticket/8257

**Comment by rebnridgway** [comment]
This also causes problems in #error directives, which is more of an issue.  If we can't use apostrophes in error messages they can't be grammatically correct!

**Comment by danmar** [comment]
I fixed the `#error` handling. @amai2012 would it be ok to rewrite your code like:

    void func() {
    #if 0
    #error it's a bug
    #endif
    }

**Comment by amai2012** [comment]
For me and my code I'd be willing to adopt that pattern. OTOH it was not my code, so that problem may persist.
Based on the examples from trac I assume that your fix addresses the most common pattern, though.

**Comment by danmar** [comment]
I close this until we have somebody who really wants to have this. Feel free to reopen this.
