### ISSUE TITLE
[transfer from cppcheck trac #8150] crash for '#if 3 > sizeof(int'

### ISSUE THREAD

**Issue by hexcoder-** [danmar/simplecpp#95]
While fuzzing cppcheck-1.80 with afl-fuzz under Linux Ubuntu 17.04,
 this stimulus
`#if 3 > sizeof(int`
caused cppcheck to access a null pointer (tok2->op) in this code snippet in simplecpp.cpp at lines 
1857-1858:
`while (tok2->op != ')')`
                `tok2 = tok2->next;`

Suggested change is 
`while (tok2 && tok2->op != ')')`

**Comment by danmar** [comment]
did you try it? I think this has been fixed already. see f704c1b42ff5b83cf831e03b7170dc4e1c91ce5b.

**Comment by danmar** [comment]
I close this. Feel free to reopen if you can reproduce with git HEAD. I "bumped" simplecpp in cppcheck also so cppcheck should not crash neither.
