### ISSUE TITLE
valueTok is not guaranteed to be assigned in Macro::parseDefine()

### ISSUE THREAD

**Issue by Dmitry-Me** [danmar/simplecpp#97]
`Macro::parseDefine` goes like this:

    if (!sameline(nametoken, argtok)) {
        endToken = argtok ? argtok->previous : argtok;
        return false;
    }
    valueToken = argtok ? argtok->next : NULL;

If control gets to `return false` then `valueToken` is not set. That's CID 1360406 in cppcheck.

I guess the fix would be

         valueToken = NULL;
         return false;
    }

**Comment by danmar** [comment]
yes that fix looks appropriate.

**Comment by Dmitry-Me** [comment]
Do you want a patch, a PR or will you fix it yourself?

**Comment by danmar** [comment]
I would like a PR
